# Site settings
title: Eduardo Cordova
twitter_username: eduardoawakens
name: Eduardo Cordova

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: CV
   url: https://raw.githubusercontent.com/eduardocordova/eduardocordova.github.io/master/cv/EACM_CV_2021_EN.pdf
 - title: GitHub
   url: https://github.com/eduardocordova
 - title: LinkedIn
   url: https://www.linkedin.com/in/eduardo-cordova-mancheno/


#Any buzzword skills you want to include
skills:
 - Java
 - Python
 - Machine Learning
 - NLP
 - Text summarization
 - Web
 - Mobile
 - RPA
 - Design
 #optional
stackoverflow:
   profileurl:
   flairimageurl: ./img/pic.jpg
   
#Work experience is required
roles:
 - title: Analyst Programmer
   start: 2019
   end: 2021
   employer: Maint S.A.
   description: Obtained certifications in RPA (UIPath, Automation Anywhere) and Analytics (Vertica).
 - title: Consultant
   start: 2015
   end: 2016
   employer: Industria Solex
   description: Collection, analysis, interpretation, presentation, and organization of data.
 - title: Junior Designer and Developer
   start: 2013
   end: 2014
   employer: Crifa Cia. Ltda.
   description: Web design, Web Development. Obtained Zend PHP certification
 - title: Coordinator
   start: 2010
   end: 2013
   employer: Guayaquil Construction Chamber
   description: Responsible for digital identity, audiovisual assignments, webmaster, social networks management and organization of events.
 - title: Post-Producer
   start: 2010
   end: 2010
   employer: Canal Uno
   description: Motion Graphics, 3D animations , TV Shows Promos.
 - title: Casting Director / Editor
   start: 2009
   end: 2010
   employer: Canal Uno
   description: Responsible for the technical area, castings, edit and post-production of TV spots.
 - title: Editor
   start: 2008
   end: 2009
   employer: Xtreme Film Production
   description: Responsible for video edition and post production of TV program "Casa y Diseño", International Ecuavisa.

#Education is required
education:
 - level: Master of Science (M.Sc.)
   date: 2018
   subject: Computer Science and Engineering
   school: Politecnico di Milano
   
intro: |
  I’m a person closely related to new technologies and deep learning with an interest in NLP.<br/><br/>
  I've recently worked in RPA and CRM projects.<br/><br/>
  Before that I worked in different industries, gathering experience in many disciplines like multimedia, web development, video and design.<br/><br/>
